on: [pull_request]

jobs:
  hello_world_job:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: A job to say hello
    env:
      GITHUB_TOKEN: ${{ secrets.TEST_ACTION_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AZURE_URL: ${{ secrets.AZURE_URL }}
    steps:
      - name: Hello world action step
        id: hello
        uses: danwill89/hello-world-javascript-action@1.22
        with:
          who-to-greet: 'Dan'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
