on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI.KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.TEST_ACTION_TOKEN }}
          OPENAI.API_TYPE: 'azure'
          OPENAI.API_VERSION: '2023-07-01-preview'
          OPENAI.API_BASE: '${{ secrets.AZURE_BASE_URL }}'
          OPENAI.DEPLOYMENT_ID: 'turbo301'
          CONFIG.MODEL: 'gpt-35-turbo'